server:
  port: 80
  error:
    include-message: always
spring:
  application:
    name: scraping-service
scraper:
  config:
    adaptor:
      enable-debug: false
    service:
      enable-debug: false
    jsoup:
      timeout: 10000
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error
